# Modify the ConfigMap adding an extra annotation:
# kubectl edit configmap disallow-latest-tag
# Verify Sveltos updates it
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: deploy-kyverno-policies
spec:
  dependsOn:
  - deploy-kyverno
  clusterSelector:
    matchLabels:
      env: prod
  policyRefs:
  - name: disallow-latest-tag
    namespace: default
    kind: ConfigMap
  - name: disallow-empty-ingress-host
    namespace: default
    kind: ConfigMap

