# This is used to demo configuration drift detection.
# After applying this ClusterProfile, while pointing to managed cluster:
#
# kubectl delete deployments  -n nginx            nginx-latest-nginx-ingress-controller
# => verify deployment is recreated
#
# kubectl edit deployments  -n nginx            nginx-latest-nginx-ingress-controller
# remove the annotation sveltos: drift-test => verify annotation is added back
#
# kubectl edit deployments  -n nginx            nginx-latest-nginx-ingress-controller
# change replicas to 3 => this never gets rewritten because of driftExclusions
#
# kubectl edit deployments  -n nginx            nginx-latest-nginx-ingress-controller 
# remove the annotation sveltos: drift-test => verify annotation is added back while replicas is still 3
#
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: nginx
spec:
  clusterSelector:
    matchLabels:  
      env: prod
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://helm.nginx.com/stable/
    repositoryName:   nginx-stable
    chartName:        nginx-stable/nginx-ingress
    chartVersion:     1.3.1 
    releaseName:      nginx-latest
    releaseNamespace: nginx
    helmChartAction:  Install
    options:
      upgradeOptions:
        resetValues: true
    values: |
      controller:
        annotations:
          sveltos: drift-test
  driftExclusions:
  - paths:
    - "/spec/replicas"
    target:
      kind: Deployment
